"""set file workspace_id cascade

Revision ID: e5262f262a06
Revises: 7bd87c83c841
Create Date: 2025-07-14 11:02:32.999359

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5262f262a06"
down_revision: Union[str, Sequence[str], None] = "7bd87c83c841"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("files_workspace_id_fkey"), "files", type_="foreignkey")
    op.create_foreign_key(
        op.f("files_workspace_id_fkey"), "files", "workspaces", ["workspace_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("files_workspace_id_fkey"), "files", type_="foreignkey")
    op.create_foreign_key(
        op.f("files_workspace_id_fkey"), "files", "workspaces", ["workspace_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###
