"""change files field

Revision ID: 7bd87c83c841
Revises: 58ecdd60af51
Create Date: 2025-07-04 11:16:18.539845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd87c83c841'
down_revision: Union[str, Sequence[str], None] = '58ecdd60af51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('files', 'channel_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('files_channel_id_idx'), 'files', ['channel_id'], unique=False)
    op.drop_constraint(op.f('files_workspace_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_channel_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_workspace_id_fkey'), 'files', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('files_channel_id_fkey'), 'files', 'channels', ['channel_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('files_channel_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_workspace_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_channel_id_fkey'), 'files', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('files_workspace_id_fkey'), 'files', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('files_channel_id_idx'), table_name='files')
    op.alter_column('files', 'channel_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('files', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
