version: "3.9"

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  db2:
    image: postgres:14-alpine
    container_name: postgres2
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres2
      - POSTGRES_USER=postgres2
      - POSTGRES_DB=postgres2
    volumes:
      - postgres_data2:/var/lib/postgresql/data


volumes:
  postgres_data2:
    driver: local